#!/usr/bin/env bash

iDIR="$HOME/.config/scripts/icons"
notification_timeout=1000

# Get brightness
get_backlight() {
	echo $(brightnessctl -m | cut -d, -f4)
}
get_icon(){
  icon="$iDIR/brightness.png"
  current=$(get_backlight | sed 's/%//')
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:brightness_notif -h int:value:$current -u low -i "$icon" "Brightness : $current%"
}

# Change brightness
change_backlight() {
	brightnessctl s "$1" && get_icon && notify_user
}

# Execute accordingly
case "$1" in
	"--get")
		get_backlight
		;;
	"--inc")
		change_backlight "+10%"
		;;
	"--dec")
		change_backlight "10%-"
		;;
	*)
		get_backlight
		;;
esac
